### ISSUE TITLE
Kafka consumer factory error

### ISSUE THREAD

**Issue by amitoj** [AxonFramework/extension-kafka#20]
Running the example I'm getting following error message on startup

> The bean 'kafkaConsumerFactory', defined in class path resource [org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfiguration.class] and overriding is disabled.
> 
> Action:
> 
> Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Setting 
> spring.main.allow-bean-definition-overriding=true

results in 

> Parameter 0 of method kafkaFetcher in org.axonframework.extensions.kafka.autoconfig.KafkaAutoConfiguration required a bean of type 'org.axonframework.extensions.kafka.eventhandling.consumer.ConsumerFactory' that could not be found.

**Comment by smcvb** [comment]
@amitoj would you mind sharing how you are running the sample at this moment?

If you are using the Axon Kafka Extension version from Maven Central, I would expect this issue at the moment to be honest.

I've solved this on the `master` branch by forcefully setting the bean name of the consumer factory and producer factory which, as you've noticed, as they stand clash with Spring's `kafkaConsumerFactory` and `kafkaProducerFactory` beans.

I would expect that if you'd clone _this_ entire repository and run it from your preferred IDE that a local build of the extension would be used. This local build would be up to date regarding the suggested bean name change, thus resolving the issue.

Due to the above assumption I will be closing this issue as a question. If my assumptions are incorrect, feel free to comment on this ticket again.
