### ISSUE TITLE
Is this being actively maintained?

### ISSUE THREAD

**Issue by somilbansal86** [AxonFramework/extension-kafka#4]
Hi, We are planning to use this is production but its concerning that there has been not activity on this for sometime now? When is this schedule to go in production and if so, is this project being actively maintianed ?

**Comment by smcvb** [comment]
Thanks for you interest in the Kafka extension for Axon Framework, @somilbansal86.

To answer your question, you've rightfully noted there hasn't been a lot of work on this repository for some time now.

**Comment by abuijze** [comment]
Hi @somilbansal86,
this module has started as a community contribution. While the original authors have committed to continuing development, this is subject to their availability to work on it.
While we (at AxonIQ) also plan to put effort in continuing development ourselves, our time is also limited, and we currently face conflicting priorities.

I will close this issue, at it is a question, rather than active work, but feel free to comment on it.

**Comment by somilbansal86** [comment]
Thanks Allard, Appreciate your prompt response.
