### ISSUE TITLE
ETA for final release of version 4.0?

### ISSUE THREAD

**Issue by anno1985** [AxonFramework/extension-kafka#7]
Is there a roadmap yet for releasing a version 4.0 (final) of the project?
Is the RC2 considered stable? :)

**Comment by smcvb** [comment]
Work on pulling the Kafka Extension out of it's release candidate state is eminent.
Per default, we do not give exact dates on this.
I can however confirm it will occur prior to another minor release like 4.2, which we release last week for Axon Server, Axon Framework, etc.

As the nature of this issue is a question, I will be closing it as such.
