### ISSUE TITLE
KafkaAutoConfiguration should not be auto-configured after InfraConfiguration

### ISSUE THREAD

**Issue by muammeryucel** [AxonFramework/extension-kafka#82]
### Basic information
* Axon Framework version: 4.4
* JDK version: 11
* Kafka Extension version: 4.0-RC3
* Complete executable reproducer if available (e.g. GitHub Repo): https://github.com/muammeryucel/axon-kafka-test.git

KafkaEventPublisher bean, which is responsible for publishing events to Kafka, is configured by KafkaAutoConfiguration, and while it being created, the factory method also registers a subscribing or tracking event processor to the event processing module. EventProcessingModule's initialize method handles this kind of registrations and prepares the module to distribute events to the event handlers. For this purpose, EventHandlerRegistrar bean, which is defined by InfraConfiguration, initialises the event processing module in its afterPropertiesSet method. In order to handle events properly, all event handlers must be registered before initilization of the event processing module. To handle events by KafkaEventPublisher, the publisher bean must be created before EventHandlerRegistrar, but there is no explicit dependency between them. This may work correctly by coincidence, but we can't be certain.

### Steps to reproduce
To reproduce the problem, I implemented a test code: https://github.com/muammeryucel/axon-kafka-test.git. 

You can also use axon-kafka-example project. For testing the situation mentioned above, I added the following amqp dependencies at the end of dependencies section of the pom.xml:
```
        <dependency>
            <groupId>org.axonframework.extensions.amqp</groupId>
            <artifactId>axon-amqp-spring-boot-starter</artifactId>
            <version>4.4</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
```
By doing this, I managed to give more priority to InfraConfiguration which is marked to get auto-configured before AMQPAutoConfiguration and this was enough to confuse the auto-configuration ordering. When I run the application, I observed that, KafkaEventPublisher became unable to handle event messages and publishing to Kafka stopped.

As a solution, I created an spring-autoconfigure-metadata.properties file inside src/resources/META-INF directory with containing the following lines, and publishing to Kafka started again after restarting the application:

```
org.axonframework.extensions.kafka.autoconfig.KafkaAutoConfiguration=
org.axonframework.extensions.kafka.autoconfig.KafkaAutoConfiguration.AutoConfigureBefore=org.axonframework.springboot.autoconfig.InfraConfiguration
```

### Expected behaviour

It should publish the messages to Kafka.

### Actual behaviour

It doesn't publish the messages to Kafka.

### Proposed Solution

If there is a dependency between auto-configuration order of these beans, it must be declared explicitly. To do this KafkaAutoConfiguration class must have this annotation: **@AutoConfigureBefore(InfraConfiguration.class)**

As we look at the problem from more general point of wiew, we can easily see that EventProcessingModule is supposed to get initialized just before event processing is started. And also if we debug the initialize method, we can see this method is called more than one time during application bootstrap. EventHandlerRegistrar's afterPropertiesSet method also makes this initialization process thightly coupled with its bean initialization process. I think, EventProcessingModule's "initialize" method should be called only once just before starting event processing and therefore, I propose that,  "initialize" method-call should be moved from "afterPropertiesSet" method to "start" method, if it is possible. I didn't give a try, but it seems to me more reasonable.

**Comment by smcvb** [comment]
Thanks for figuring this out and providing such a detailed page of information @muammeryucel! 
Flaky event handling behaviour has been spotted, also by others, but time and effort didn't allow us to dive into it. I'll have a look at your sample project to validate the stated solution just to be sure, but I am trusting you hear because clearly you've put a lot of thought into this.

The last note you've placed on the `EventProcessingModule` being invoked twice is something we are aware off. Although we could just try to solve that one problem, we actually would like to rewrite the `axon-spring` module entirely. There is a multitude of things we're not happy with in there which simply justify this action. You can however imagine it would take up quite a large chunk of our time, something we haven't found the moment for just yet. Bringing this to light however only further signals the necessity.

Having said that, I'll check out your sample project. If it works, I'd like to ask you to provide a PR to solve the problem. Mainly saying this as I think you deserve the credits for figuring this out. Anyhow, I'll come back to you in a couple.

**Comment by smcvb** [comment]
I've tested both suggested way to reproduce, and I was able to replay both successfully on my machine.

Thus, I think we have a solution in place, which I'd very much would like to see as a PR!
Granted, if you have the time to provide a pull request to the Kafka Extension.
Let me know if you are up for that; if not, I'll add the auto configure configuration myself.

**Comment by muammeryucel** [comment]
I created a PR (https://github.com/AxonFramework/extension-kafka/pull/83), but its build process has been pending on travis for a while. When I took a look at previous builds, I noticed that, the last build also had failed.

As I've seen and you've mentioned, some components about event processing module seem a bit complicated. If there is a forum, or something like this, about rewriting axon-spring module, can you share its link here, if possible. I would be very happy if I could follow technical discussions about the new implementation.

**Comment by smcvb** [comment]
Noted, thanks pointing it out. TravisCI sometimes doesn't act nicely due to the large number of jobs they have to process. It can thus simply take a couple of hours before a build can actually start. Similarly, there's sadly a time based test in the Kafka Extension which sometimes succeeds, sometimes it doesn't. The PR you've provided I believe hit both predicaments, which I'd simply call "bad luck". I've however forced another run on TravisCI, trusting it'll succeed this time around.

We indeed do have a forum for discussion. This is AxonIQ's Discuss forum, which you can find [here](https://discuss.axoniq.io/). As it stands there is however no issue on Axon Framework issue tracker referring to this intended `axon-spring` overhaul. Main reason: we're still debating about it, ensure whether we should start this ASAP or in a year from now. Regardless I can assert you that as soon as we will start working on this, an issue/PR will follow, so that anybody in the community can trail the progress. Similarly, it's perfectly fine to start a thread on the forum to chat about ideas too.
